"""TSV resource loader functions for compiling languages, phonologies, and schemes."""

from __future__ import annotations

from collections.abc import Callable
from importlib import resources
from importlib.resources.abc import Traversable
from pathlib import Path, PurePath
from typing import TYPE_CHECKING

from ...core.language import Language
from ...loader import load_phonology, load_scheme
from ..exceptions import ParseError, ReadError
from .parsers.phonology import parse as parse_phonology
from .parsers.scheme import parse as parse_scheme
from .reader import read

if TYPE_CHECKING:
    from ...core.facades.phonology import Phonology
    from ...core.facades.scheme import Scheme
    from ...core.models.representation import (
        PhonologyRepresentation,
        SchemeRepresentation,
    )


def load_language(
    language_id: str,
    directory: str | Traversable | None = None,
    phonology_file_name: str = "phonology.tsv",
    schemes_folder_name: str = "schemes",
) -> Language[PhonologyRepresentation]:
    """Loads a full language representation along with its phonology and scheme specs.

    Args:
        language_id: Identifier of the language directory to load.
        directory: Optional root directory containing language specs. Defaults to
            `yumcha.data`.
        phonology_file_name: Filename for the phonology TSV file. Defaults to
            "phonology.tsv".
        schemes_folder_name: Subfolder name containing scheme TSV files. Defaults to
            "schemes".

    Returns:
        A populated `Language` object containing phonology and associated schemes.

    Raises:
        ReadError: If reading any TSV file fails due to I/O issues.
        ParseError: If parsing any TSV file content fails due to validation errors.
    """
    if directory is None:
        directory = resources.files("yumcha.data")
    elif isinstance(directory, str):
        directory = Path(directory)

    language_directory = directory / language_id
    phonology_resource = language_directory / phonology_file_name

    try:
        phonology = load_phonology_from_tsv(phonology_resource)
    except OSError as e:
        raise ReadError(phonology_file_name, e) from e
    except ValueError as e:
        raise ParseError(phonology_file_name, e) from e

    language = Language(phonology)
    schemes_directory = language_directory / schemes_folder_name

    if schemes_directory.is_dir():
        for scheme_resource in schemes_directory.iterdir():
            if not scheme_resource.is_file():
                continue
            try:
                scheme = load_scheme_from_tsv(scheme_resource)
            except OSError as e:
                raise ReadError(scheme_resource.name, e) from e
            except (ValueError, TypeError) as e:
                raise ParseError(scheme_resource.name, e) from e

            language.add_scheme(scheme)

    return language


def _load_from_tsv[DataT, ReturnT](
    resource: str | Traversable,
    id: str | None,
    id_fallback: Callable[[Traversable], str],
    parse_fn: Callable[[str, list[str], list[list[str]]], DataT],
    load_fn: Callable[[DataT], ReturnT],
    error_label: str,
) -> ReturnT:
    """Reads, parses, and converts TSV data using the given helper pipeline functions.

    Args:
        resource: Resource location to read TSV content from.
        id: Optional identifier string. If `None`, `id_fallback` is called.
        id_fallback: Callable function that generates an identifier from the resource.
        parse_fn: Callable function that parses headers and raw data rows into spec data.
        load_fn: Callable function that builds the final object from parsed spec data.
        error_label: Label used to qualify validation errors if identifier resolution fails.

    Returns:
        The instantiated domain object generated by `load_fn`.

    Raises:
        ValueError: If the derived identifier is empty or not a valid Python identifier.
    """
    if isinstance(resource, str):
        resource = Path(resource)
    resource_id = id if id is not None else id_fallback(resource)

    if not resource_id or not resource_id.isidentifier():
        raise ValueError(
            f"{error_label} {resource_id!r} must be a valid Python identifier"
        )

    headers, data = read(resource)
    parsed_data = parse_fn(resource_id, headers, data)
    return load_fn(parsed_data)


def load_phonology_from_tsv(
    resource: str | Traversable,
    language_id: str | None = None,
) -> Phonology[PhonologyRepresentation]:
    """Loads phonology data from a TSV resource file into a Phonology instance.

    Args:
        resource: A `Traversable` resource pointing to the phonology TSV file.
        language_id: Optional language identifier string. If `None`, it is inferred from
            the parent folder name of the resource.

    Returns:
        A loaded `Phonology` instance.

    Raises:
        ValueError: If `language_id` is not a valid Python identifier or TSV parsing fails.
    """

    def id_fallback(resource: Traversable) -> str:
        return PurePath(str(resource)).parent.name

    return _load_from_tsv(
        resource,
        language_id,
        id_fallback,
        parse_phonology,
        load_phonology,
        "folder name",
    )


def load_scheme_from_tsv(
    resource: str | Traversable,
    scheme_id: str | None = None,
) -> Scheme[SchemeRepresentation]:
    """Loads scheme data from a TSV resource file into a Scheme instance.

    Args:
        resource: A `Traversable` resource pointing to the scheme TSV file.
        scheme_id: Optional scheme identifier string. If `None`, it is inferred from the
            resource filename (without extension).

    Returns:
        A loaded `Scheme` instance.

    Raises:
        ValueError: If `scheme_id` is not a valid Python identifier or TSV parsing fails.
    """

    def id_fallback(resource: Traversable) -> str:
        return resource.name.rsplit(".", 1)[0]

    return _load_from_tsv(
        resource,
        scheme_id,
        id_fallback,
        parse_scheme,
        load_scheme,
        "file name",
    )
