direction: right

JP: Jyutping
LP: Cantonese\nPhonology {
  shape: circle
}
ILE: Institute of \nLanguage in Education\n(ILE) Scheme
BR: Braille
PY: Pênkyämp
Y: Yale
SL: Sidney Lau
SLW: S. L. Wong
MW: Meyer–Wempe

JP <-> LP
ILE <-> LP
BR <-> LP
PY <-> LP
LP <-> Y
LP <-> SL
LP <-> SLW
LP <-> MW
