direction: right

style: {
  fill: transparent
}

Sidney Lau: {
  1°
  1
}

IR: Intermediate\nRepresentation {
  "[˥]"
  "[˥˧]"
}

Jyutping.1

Sidney Lau.1° <-> IR."[˥]" <-> Jyutping.1
Sidney Lau.1 <-> IR."[˥˧]"
IR."[˥˧]" -> Jyutping.1: One-way {
  style.stroke: yellow
}
