direction: right

style: {
  fill: transparent
}

Sidney Lau.1°
Sidney Lau.1
Intermediate\nRepresentation."[˥]"
Intermediate\nRepresentation."[˥˧]"
Jyutping.1

Sidney Lau.1° <-> Intermediate\nRepresentation."[˥]" <-> Jyutping.1
Sidney Lau.1 <-> Intermediate\nRepresentation."[˥˧]"
Intermediate\nRepresentation."[˥˧]" -> Jyutping.1: One-way {
  style: {
    stroke: yellow
  }
}
