from __future__ import annotations

import inspect
import math
from collections.abc import Iterable, Iterator
from itertools import product
from typing import TYPE_CHECKING, Any, Protocol, TypeVar

from .core.pattern_tuple import PatternTuple

if TYPE_CHECKING:
    from .language import Language


T = TypeVar("T")


class ProgressBarWrapper(Protocol):
    """Protocol signature for progress bar wrapper callables (e.g., `tqdm`)."""

    def __call__(
        self,
        iterable: Iterable[T],
        *,
        total: int | None = None,
        **kwargs: Any,
    ) -> Iterable[T]: ...


class SyllableTable:
    """Generates combinatorial syllable matrix tables for a given language.

    Iterates over all phonologically possible sound combinations generated by taking
    the Cartesian product of the language's character sets, optionally converting each
    pattern tuple to all available romanization/orthographic schemes.

    Attributes:
        lang (Language): The target language model instance.
        scheme_item_counts (list[int]): Tracked counts of non-empty conversions produced for each scheme.
        progress_bar (ProgressBarWrapper | None): Optional progress bar wrapper function or class.
    """

    lang: Language
    scheme_item_counts: list[int]
    progress_bar: ProgressBarWrapper | None

    def __init__(
        self,
        lang: Language,
        progress_bar: ProgressBarWrapper | None = None,
    ):
        """Initializes a SyllableTable generator.

        Args:
            lang: Target `Language` model instance.
            progress_bar: Optional callable conforming to `ProgressBarWrapper` to wrap iteration.
        """
        self.lang = lang
        self.progress_bar = progress_bar

        scheme_ids = tuple(self.lang.schemes)
        self._scheme_ids = scheme_ids
        self.scheme_item_counts = [0] * len(scheme_ids)

    def __iter__(self) -> Iterator[list[str]]:
        """Generates row-by-row string representations for all phonological combinations.

        Yields:
            A list of string elements representing one row, starting with the intermediate
            phonological representation followed by conversions under each registered scheme.
        """
        scheme_ids = tuple(self.lang.schemes)
        self.scheme_item_counts = [0] * len(scheme_ids)

        pron_tuples = product(*self.lang.phonology.charsets_sorted)
        progress_bar = self.progress_bar

        if progress_bar is not None:
            signature = inspect.signature(progress_bar)
            if "total" in signature.parameters or any(
                p.kind == p.VAR_KEYWORD for p in signature.parameters.values()
            ):
                pron_tuples = progress_bar(pron_tuples, total=self.total_rows)
            else:
                pron_tuples = progress_bar(pron_tuples)

        for pron_tuple in pron_tuples:
            pattern_tuple = PatternTuple(pron_tuple)
            row = [pattern_tuple.to_string()]

            for idx, scheme_id in enumerate(scheme_ids):
                item = self.lang.to_scheme(scheme_id, pattern_tuple, True, False)
                if item:
                    row.append(str(item))
                    self.scheme_item_counts[idx] += 1
                else:
                    row.append("")

            yield row

    @property
    def scheme_ids(self) -> tuple[str, ...]:
        """Gets the registered scheme identifiers for the active language.

        Returns:
            A tuple of scheme ID strings.
        """
        return tuple(self.lang.schemes)

    @property
    def headers(self):
        """Gets table column headers.

        Returns:
            A list of column names, starting with "IR" followed by scheme IDs.
        """
        return ["IR", *self.lang.schemes]

    @property
    def footers(self):
        """Gets summary counts for table footers.

        Returns:
            A list where the first element is total evaluated rows, followed by
            counts of non-empty representations for each scheme column.
        """
        return [self.total_rows, *self.scheme_item_counts]

    @property
    def total_rows(self) -> int:
        """Calculates the total possible combination count (Cartesian product length).

        Returns:
            Total row count as an integer.
        """
        return math.prod(len(c) for c in self.lang.phonology.charsets_sorted)
